### ISSUE TITLE
Reporter Sometimes Fails with event data must contain eventType field. []

### ISSUE THREAD

**Issue by AngellusMortis** [newrelic/junit-reporter-action#10]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

Sometimes the report just silently fails (the action still passes, but not `TestRun` data is generated in New Relic). 

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

Run reporter. A lot.

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

Action should never fail.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

There are basically no logs for the action, but when it does "failure" this is the only log line:
```
level=fatal msg="event data must contain eventType field. []"
```

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

Image of the total number of failures vs. test runs for the last week. The runs include successes and failure since I could not think of a good one to subtract the failures.

![image](https://github.com/newrelic/junit-reporter-action/assets/490848/e8880053-7ea4-4bed-9146-b5da98b44f35)

**Comment by cpernot-hf** [comment]
+1
On our side, this error happens nearly all the time, but if I use the newrelic-cli directly, the problem disappears...

**Comment by AngellusMortis** [comment]
I no longer care.
